### ISSUE TITLE
Not compatible with Hogfather

### ISSUE THREAD

**Issue by DeanCording** [Cilyan/dokuwiki-plugin-dontfeedtemplates#2]
PHP Fatal error:  Declaration of action_plugin_dontfeedtemplates::register(Doku_Event_Handler &$controller) must be compatible with dokuwiki\\Extension\\ActionPlugin::register(Doku_Event_Handler $controller) in /var/www/dokuwiki/lib/plugins/dontfeedtemplates/action.php on line 0

**Comment by Cilyan** [comment]
Unfortunately, I don't have a DokuWiki instance any more to test. But https://github.com/Cilyan/dokuwiki-plugin-dontfeedtemplates/pull/1 should have corrected that already. Please update the plugin if it isn't.

If it still fail, please try to change

```php
public function handle_feed_item_add(Doku_Event &$event, $param) {
```
to
```php
public function handle_feed_item_add(Doku_Event $event, $param) {
```
(remove the & character) at line 65 of `action.php` and report if that works.

Thank you

**Comment by Cilyan** [comment]
See https://www.patreon.com/posts/20638123 that was corrected by https://github.com/Cilyan/dokuwiki-plugin-dontfeedtemplates/pull/1
